### ISSUE TITLE
Update help text

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#102]
Some of the Preferences are unintuitive and require further explanation, particularly those related to audio description. Should draft some text for the Help dialog and run it by users to see if they find it helpful.

**Comment by kensgists** [comment]
One thing Corey and I discussed earlier was grouping, indenting, and making some selections dependent on others, in order to help with the cognitive overload. How about this, from the top of the dialog:

- Captions on by default
- Recorded audio description on by default
- Synchronized transcript on by default

Text-based audio description (grouping)
- Use text-based description, if available
    - Pause video when text-based description starts (checkbox disabled if text-based not selected)
    - Make text-based description visible (checkbox disabled if text-based not selected)

Synchronized transcript (grouping)
- Highlight transcript as media plays
- Keyboard-enable transcript (make it "tabbable")

Keyboard shortcut key modifiers (grouping)
- Alt
- Control
- Shift
(this could be made horizontal to save space)

Later, when styling of captions is added, another grouping could be created.

I know this makes the dialog longer, but I think the groupings make the logic clearer.

We might also consider removing all of the "on by default" settings and hard code the preference to always turn on captions if they are available. Recorded audio and transcript would always need to be enabled by the user, and/or those preferences could be set silently in a cookie if the user turned them on previously.

**Comment by terrill** [comment]
I like the idea of grouping, and I think it's ok to have scrollable content within the dialog. I would argue though for keyboard shortcuts at the top, since those are handy for quick reference, whereas everything else will require reading.

**Comment by terrill** [comment]
I created a wiki page with draft help text: 
https://github.com/ableplayer/ableplayer/wiki/Help-text-(displayed-in-Help-dialog)

Next steps: 
1. Chisel away at it so we're communicating everything clearly but efficiently.
2. Do some user testing for additional feedback and further fine-tuning.

**Comment by terrill** [comment]
@kensgists I like your idea of removing all of the "on by default" preferences (captions, descriptions, transcript). These can be toggled on/off via buttons on the control bar. Also I think we can remove "show sign language if available". If sign language is available, I think all users should see the button - that helps to raise awareness about the need.

**Comment by terrill** [comment]
Complete as of 91046a898a58142a103b6a97673fc4be06680597
Preferences is now divided into four distinct dialogs, triggered by a popup menu from the Preferences button. This frees up screen real-estate in each of the dialogs, so help text was added to the Preferences dialogs where it's needed most. The separate Help button has been removed, which has the added benefit of freeing up space on the control bar.
