### ISSUE TITLE
Improve sign language drag/drop and resize feature

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#106]
When building 8da3b9a592aaa4c922184d3515fa65bf95601fc3 I experimented with this using Gez Lemon's article [Accessible Drag and Drop Using WAI-ARIA](https://dev.opera.com/articles/accessible-drag-and-drop/) as a guide. However, I ultimately scrapped this as it didn't seem to be well supported by screen readers, and created more noise than benefits. Requires further testing before implementing.

**Comment by terrill** [comment]
Overall the current implement is a little clumsy. Need to: 
1. Add ability to drag the window without first selecting "Move" from the menu. 
2. Add ability to resize the window by dragging a corner. 
3. Improve keyboard-accessible drag - it's currently choppy  
4. Add ARIA support, as explained in this original issue

**Comment by Egyrs** [comment]
We are working on that:
1.- Is done, with an option to embed it automatically
2.- This was done in my first version and will be in the new version
3.- What do you mean by "choppy"?
4.- We will test it with 5 screen-reader users.

**Comment by terrill** [comment]
"Buggy" might actually be a better word to describe the keyboard interface, rather than "Choppy". Here's what I'm experiencing: 
A. User tabs to the menu button in the sign language div. 
B. If user presses Enter, the submenu appears as expected. If they select Move from the submenu, the sign language div jumps to a new location before they start moving it. That jump is a bug. Also, the first time they press an arrow key, the sign language div moves down and right, regardless of which arrow key was pressed (another bug). 
C. If users attempts to trigger the sign language submenu by pressing space bar, that should open the submenu just as Enter does, but that's not working. Instead it has one of two effects, depending on context: 
  1.  Automatically selects "Move" and the sign language div goes into Move mode without ever displaying the submenu. 
  2. Automatically plays/pauses the media.

**Comment by Egyrs** [comment]
Good description, yes. We will work on it.

**Comment by terrill** [comment]
Thanks @Egyrs !

**Comment by terrill** [comment]
Hi @Egyrs any progress on this issue? I thought I might devote some time to it this week, but not if you've already done so. Thanks!

**Comment by Egyrs** [comment]
Hi @terill and sorry for the delay in the response:
The response is: Yes and not :-)
2 is easy, that's in my original version, but forgot to add it to the latest version on which we are working.
3 in the most part. 3B:  "1 & 2 is easy, that's in my original version, but forgot to add it to the latest version on which we are working." This is because the dot line added to show that is movable now.
"Also, the first time they press an arrow key, the sign language div moves down and right, regardless of which arrow key was pressed (another bug)." We can't found why :-(
C is fixed.
You can see it at: http://sidar.org/ableplayer2/tests/testJulian_es.html
We are testing the ARIA with 5 persons from several countries. I don't have all the answers yet. I hope tomorrow.

**Comment by terrill** [comment]
Done in f47847e5252f52f52e46169bdd9a2402a5c7729b
