### ISSUE TITLE
full screen youtube video , the toolbar cannot disappear

### ISSUE THREAD

**Issue by KeyHui** [ableplayer/ableplayer#108]
full screen youtube video , the toolbar cannot disappear

**Comment by kensgists** [comment]
Additional issues with this: Toolbar controls not responding to mouse clicks and toolbar positioned in vertically in middle of video.

**Comment by terrill** [comment]
@KeyHui the toolbar actually doesn't disappear at all, regardless of whether the player is in full screen mode. That's a design decision, but on our to-do list to add as an optional feature (see #119 )

@kensgists the controller positioning bug in full screen YouTube is now fixed with 8a6ee756a90768fd8cb8fb4005d020d8433a2318
