### ISSUE TITLE
WebVTT parse errors

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#115]
There are at least two problems with the WebVTT parser: 

1. It expects content in the cue payload. If a cue block consists solely of cue timings followed by a blank line (i.e., has no content) Able Player chokes. 

2. It expects only one blank line between cue blocks. If there are multiple blank lines, Able Player chokes. 

This might be a case of the [WebVTT spec](http://dev.w3.org/html5/webvtt) evolving since the parser was developed. Since the spec is still a draft, it will be important for us to remain abreast of changes.

**Comment by blrichwine** [comment]
I put in a pull request with some changes to webvtt.js that address this bug by making the parser more robust to line spacing in / between cues.

**Comment by terrill** [comment]
Thanks to @blrichwine for this solution. It's been implemented in 849f7926cdba516544f6570eae5b0183814b3cce

**Comment by terrill** [comment]
Hmmm, actually looks like the parser still fails to handle multiple blank lines at the end of a WebVTT file. Do you have a moment to try to tackle that @blrichwine since the WebVTT parse logic is fresh in your mind?  That will also provide us with an opportunity to test whether I've fixed the repo's inconsistent line feed issue. If you do want to tackle this, please do so against the develop branch. Thanks!

**Comment by blrichwine** [comment]
@terrill I'll take a look.

**Comment by blrichwine** [comment]
@terrill Do you have a webvtt file with multiple blank lines at the end and a description of the problem you were seeing? 

I'm using Komodo Edit 9.0 on OSX to edit my WebVTT files and adding blank lines to the end of a WebVTT file does not appear to be creating an issue (that I notice anyway). 

I'm making edits to the ableplayer/media/wwa_captions_en_test.vtt file to do my testing.

I've tried 1, 2, 3, and 4 blank lines at the end as well as saving the file with Windows line endings (/r/n), Unix line endings (/n), and classic mac line endings (/r).

**Comment by terrill** [comment]
@blrichwine I just pushed commit 1be88af56ee06c50d7047f4ca9241c6e68b009fb to the develop branch with blank lines at the end of wwa_captions_en.vtt.  Since they're at the end of the file they really don't have a negative effect on users, but they're causing an "Unable to parse time stamp" error that appears in the browser console.

**Comment by blrichwine** [comment]
@terrill -- Ah... thanks! I'll look at that today.

**Comment by blrichwine** [comment]
@terrill -- How do you want the WebVTT parser to behave when it encounters an invalid WebVTT file. Do you want it to attempt to recover gracefully, or stop processing the WebVTT file and throw an error?

the parseCuesAnd Comments function is not eating empty lines, but rather it is calling the parseCue function when it encounters a blank line. Therefore when blank lines appear at the end of the file, the parseCuesAndComments function still calls the parseCue function. This causes the parseCue function to throw an error because there really isn't a cue it can process.

I can easily adjust the parseCuesAndComments function to only call the parseCue function when there really is a cue, and to have the parseCuesAndComments functions eat the extra blank lines.

The question is, what to do if the parseCuesAndComments function finds a line that has content but is neither a NOTE/comment or a Cue? My suggestion is to log a warning to the browser console that the WebVTT file appears invalid due to unexpected content on line such 'n such, and then keep looking for comments and cues thereby favoring robust processing over a fragile stop on any error approach.

I'll code it that way, but let me know if that isn't what you want.

**Comment by terrill** [comment]
@blrichwine I like your idea of logging a warning to the console then attempting to gracefully recover. Can you implement that on the develop branch though, rather than master? Your pull request is actually a little behind. In particular I had made some changes to scripts/webvtt.js on develop that make the VTT filename available for the console message. I think that's important since a video might have multiple VTT files.

**Comment by blrichwine** [comment]
@terrill - Ugh! I thought I was working on the develop branch. I'll look and see if I can determine what I'm doing wrong. 

I checked out the develop branch on my fork, and then committed the changes to it before making a pull request. I haven't used the pull process before and am not sure I really understand it correctly.

**Comment by blrichwine** [comment]
@terrill Ok, I've tried it once more. I apologize in advance if I'm not doing this correctly.

**Comment by terrill** [comment]
Fixed with cf21a6340c3307f10ca569488cab1be41466ef7f
