### ISSUE TITLE
Tooltips sometimes don't show -- timing issue

### ISSUE THREAD

**Issue by kensgists** [ableplayer/ableplayer#122]
If I mouse over or tab through the controls quickly, sometimes a tooltip will not display. It appears to be a timing issue, with one tooltip attempting to spawn while another is already visible.

**Comment by terrill** [comment]
Currently there's only one tooltip div that's shared by all the buttons so only one can be visible at a time. When a button has focus, the div's position is calculated based on the position of the button, then it's shown for 4 seconds, and slowly fades away over 1 second. Here's the JQuery: 
button.show().delay(4000).fadeOut(1000);
 
The problem you're describing occurs if you change focus during the FadeOut. The new label was being inserted into the tooltip div while it was fading out, so it was only getting a fraction of a second of display time. I fixed this by injecting a call to jQuery stop() to stop the current fadeOut if it's occurring, before showing the new tooltip.  

Fixed in e97eabeb8e0bc94c681fa65a37abc812429d0b4b
