### ISSUE TITLE
How is Modernizr used?

### ISSUE THREAD

**Issue by jcoyne** [ableplayer/ableplayer#150]
I see it required in every example, but I'm not seeing it used in the code.

**Comment by terrill** [comment]
Modernizr is used for its html5 shiv functionality, to enable IE 8 and earlier to recognize and style HTML5 elements.  Since that's currently it's sole function you could use [html5shiv](https://github.com/aFarkas/html5shiv/) instead since that's lighter weight, but with Modernizr we could potentially use it for additional functionality. I think @npacker is using it more extensively in the [Able Player Drupal module](https://www.drupal.org/sandbox/npacker/2508441)

**Comment by jcoyne** [comment]
So, its not required if you don't have to support IE 8 and below?  IE 8 is scheduled to be EOL in January, but it still has a significant market shared, so what is ableplayer's commitment to old browsers? Is there a mandate or a methodology for determining which browsers you have chosen to support?

**Comment by terrill** [comment]
Supposedly html5shiv (and therefore, modernizr for the standalone Able Player) is not required for IE9 and higher. There might be some exceptions though, as [some markup causes IE9 to go into quirks mode]([http://stackoverflow.com/questions/14894084/html5-shiv-are-also-needed-for-ie9-in-order-to-support-html5-elements]).  

As for our commitment to older browsers, we're committed in principal, particularly given the latest (2015) [WebAIM Screen Reader User Survey Results](http://webaim.org/projects/screenreadersurvey6/#browsers), in which 12.8% of respondents were found to still use IE6, 7, or 8.  

However, last summer we [gave up on trying to support IE7](https://github.com/ableplayer/ableplayer/issues/49) because it was just too quirky to justify all the time we'd have to spend making it work well. While we'd like to support IE8, issues that effect modern browsers will likely always be our highest priority.
