### ISSUE TITLE
Able Player and iOS

### ISSUE THREAD

**Issue by milamj** [ableplayer/ableplayer#155]
Hi All,

I am noticing that with Safari and Voiceover in iOS 9.2 on an iPhone, I am having to tap the player buttons, play, stop, pause etc., multiple times before they take effect.  I am seeing this on multiple web servers, however, there is one site where I don't see this behavior, but I'm not sure what is different with that particular site.

If I visit:
http://ableplayer.github.io/ableplayer/tests/test1.html
I see thebehavior.
However, when I visit:
http://blindbargains.com/ableplayer/player/index.php?m=13520
the buttons work fine and multiple presses are not necessary.  I have seen this with and without Voiceover.  Anyone have ideas on this?  I would like to begin using the player on a radio reading service for the blind's website, but the iOS issue is one that I was hoping to figure out before implementation.

Thanks,
Jonathan

**Comment by terrill** [comment]
@milamj this issue was - I believe - fixed a while ago in Able Player. I'm not observing it in the latest release (4.x) on the live [Able Player Examples](https://ableplayer.github.io/ableplayer/demos/) site. I'm closing this issue, but if you continue to observe the problem feel free to reopen it with additional details.
