### ISSUE TITLE
How to Enable/Disable control

### ISSUE THREAD

**Issue by pmjaleel** [ableplayer/ableplayer#173]
1) I want to hide CC icon
2) I do not want to display the drop down of language selection in the transcript box.
3) How do I change the icons of play and stop etc

Please suggest

**Comment by terrill** [comment]
1) Why do you want to hide the CC icon? 

2) I assume you only want to hide the language selector if there is only one language, correct? That seems reasonable, and I've added a new issue #174

3) The font icons were created in [icomoon.io](https://icomoon.io/). You would need to replace the existing font set with a new set, careful to preserve the original names since those are referenced programatically. The icomoon font files are located in the *fonts* folder and their corresponding CSS is in *styles/ableplayer.css*. Also each icon has two corresponding PNG images (one black and one white) for browsers that don't support icon fonts. Those are located in the *images* folder.

**Comment by pmjaleel** [comment]
We do not want the CC displayed and by default it has to be off
