### ISSUE TITLE
Replace volume buttons with one volume control

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#183]
1. Clicking the button reveals a vertical slider and places focus on it 
2. Functionality and accessibility would be the same as the scrub bar. Perhaps some of the same code could be utilized. Current hotkeys for volume up (U) and down (D) would continue to function.

**Comment by terrill** [comment]
Any opinions over whether to implement a vertical slider as proposed? There seems to be a trend toward short horizontal sliders that are always visible on the control bar: 
* YouTube: Horizontal, left side (playback scrub bar is above the control bar, and spans full width) 
* Acorn Player: similar to YouTube
* WET Video Player: similar to YouTube 
* Video.js: Horizontal, hidden, left side 
* Oz Player: Horizontal, visible, right side 
* **JW Player: Vertical, hidden, right side (next to full screen button) - the style I'm proposing**
* Fluid Player: Vertical, hidden, left side
* Open University Player: louder and quieter buttons, similar to current Able Player 
* QuickTime Player (application): horizontal, left side, visible (large Play/Pause button in the center)
* Windows Media Player (application): horizontal, right side, visible (large Play/Pause button in center)

On principle I like the idea of **not** hiding controls from users, and with being somewhat consistent with what others are doing (therefore, what users may come to expect). However, Able Player has (potentially) a lot more buttons than other players (faster/slower, audio description, sign language, transcript, chapters). Therefore, control bar real estate is more valuable. 

**Any opinions?**

**Comment by kensgists** [comment]
I agree with your proposal, Terry. A couple of suggestions:

The JWPlayer vertical slider does not respond to right/left. Instead, r/l move you through the video/move the slider control. Able's implementation should be up/down / right/left agnostic. In addition the JW implementation shows "mute" only by making all of the sound curves disappear. Able's should show the mute "x" symbol, for clarity. 

One thing the JW Player does nicely is that the volume "off" is visually distinct from the first gradation of volume. When you focus the volume control, there is a distinct visual "click" upward when you move off of the "muted" position, at the very bottom of the vertical slider. 

Position: I'm not sure about the location. The reason the JW Player's position at the far right works is because the entirety of the controls set is on one line. Putting the volume on the second row, far right, in Able Player may make it a bit hard to find. What if volume were moved to the far right on the top row?. That would free up the bottom row for "disability features" (on the left) and "settings" (full screen, help, settings) on the right.

Also, a small note that you may want to consider a bug or a feature request: I get an orange rectangle on the buttons but not on the slider control when its focused. If the rectangle won't work on the slider grab handle, what about just popping up the time (as happens when I scrub with the mouse)?

**Comment by terrill** [comment]
I'm also considering adding "Prev" and "Next" buttons that can be configured to either move between chapters or between tracks in a playlist (depending on value of data-prevnext-unit). I've received quite a few requests for this feature. Those buttons could impact where to place the volume control. 

What do you think of the Articulate Storyline interface? (see attached). Volume is on the far left, before Play. Prev and Next buttons are on the far right. The scrub bar is between the two. This seems like a good functional model to me, supplemented as you suggested @kensgists with all the "accessibility features" on the second row. 
![storylinecontroller](https://cloud.githubusercontent.com/assets/912874/13432815/0b88d316-df84-11e5-820c-539ce74dfd3a.png)

**Comment by terrill** [comment]
Finished with 0bc0814e1608fd3980993fa4bc23f08a4bc3c052
Volume is on the far right, top row.
