### ISSUE TITLE
Internet Explorer - Regularly video don't start when switching with audio description

### ISSUE THREAD

**Issue by VincentHelwig** [ableplayer/ableplayer#194]
Hi, 

I didn't find a good way to test this bug, but when activating/desactivating audio description, regularly the video don't start, status say "Playing", but video show back screen.

We can play video by clicking pause button and again play button.

Bug only on IE (test on IE10 & IE11: http://ableplayer.github.io/ableplayer/tests/test16.html)

**Comment by VincentHelwig** [comment]
I tried with more recent jquery version (1.12.0), but same pb

**Comment by terrill** [comment]
Hi @VincentHelwig 

I'm not able to replicate that in IE11 using the Test16 page. If Description is **off** by default (in user Preferences), when I click the "D" button the player loads the described version and begins playing automatically. If Description is **on** by default (in user Preferences), the player starts playing the non-described version automatically, which is a bug (fixed in more recent versions on develop branch). Despite the auto-play bug, if I click the "D" button the player loads the non-described version and begins playing automatically. 

What are you experiencing that's different? And what are your description-related Preferences set to? 

Also, it's important to note that the way audio description is implemented has changed fairly significantly in more recent versions (on develop branch). Those changes will go live in v2.4, which I'm expecting to release later this month. I'm personally not seeing any problems there either, but if you have a way to test the latest develop version I can be sure to address any bugs you find.

**Comment by VincentHelwig** [comment]
Hi @terrill, 

The problem isn't on first click, or load, or depending on preferences choices, it append sometime, when you click on the "D" selected button (to play default video). I've put some logs in events.js:

```
.on('timeupdate',function() {
  console.log(thisObj.getElapsed());
  thisObj.onMediaUpdateTime();
})
```

And the result show that video is playing, and dispatch *timeupdate*, but currentTime is like paused  :
```
0.1334666
0.1334666
0.1334666
0.1334666
0.1334666
0.1334666
```

Unfortunately, I can't wait for your next release, or rebasing from develop...

**Comment by VincentHelwig** [comment]
I think there is some concurrency calls, i've fixed with adding timeout on playMedia in *onMediaNewSourceLoad* function (like in jw case), not the best solution, but it works.

Tell me if you want a PR, or if you think the bug is irrelevant

```
AblePlayer.prototype.onMediaNewSourceLoad = function () {
...
  var thisObj = this;
  setTimeout(function () {
    thisObj.playMedia();
  }, 500);
...
};
```

**Comment by terrill** [comment]
Thanks for the all the detail @VincentHelwig - that will help a lot. Probably no PR at this point but I'll investigate further and try to patch where needed in 2.3 and 2.4.

**Comment by terrill** [comment]
@VincentHelwig it looks like your work on this issue was with an older version of Able Player (2.2.1). The code for handling audio description has changed significantly in version 2.3. The latest version on the develop branch is 2.3.23. I've tested with videos of varying lengths in IE11 and can't replicate the problem you described.  If you're so inclined, it would be great if you could try the latest version on develop to see if you still encounter problems. Thanks!

**Comment by VincentHelwig** [comment]
@terrill, I know i'm working on the 2.2.1, but i've had the same problem on the current version (test on http://ableplayer.github.io/ableplayer/tests/test16.html).

**Comment by VincentHelwig** [comment]
Sorry, i've read to fast, i will try on develop asap !

**Comment by terrill** [comment]
Yeah, I haven't updated the test pages online yet - they're still using an older version.

**Comment by terrill** [comment]
@VincentHelwig have you had an opportunity to try this with the latest version? Note that I've just merged the develop branch with the master branch, so the latest version on master is now current. I've done a lot of testing over the last few weeks and personally haven't witnessed this problem, so hopefully whatever was happening has been resolved (?)

**Comment by terrill** [comment]
Closing this issue, still unable to replicate. We can re-open if anyone observes this issue again.
