### ISSUE TITLE
getNextHeadingLevel() needs tweaking

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#195]
This function, now located in scripts/misc.js, has some faulty logic. 
It does not reliably assign the best next heading level when there are multiple headings on the page.  
I've created a simple example page at http://terrillthompson.com/tests/get-next-heading.html

**Comment by jessehall3** [comment]
Replacing:
`$foundHeadings = $(this).find('h1, h2, h3, h4, h5, h6');`

With:
`$foundHeadings = $(this).children(':header');`

Solves the issue on the example page you provided. The problem is that `$(this).find('h1, h2, h3, h4, h5, h6');` is searching all levels of the parent div. After "Example 1" has been injected into the DOM, it will be included in the next `$foundHeadings` array, and the header level for "Example 2" will increment one level above "Example 1."

I didn't do any testing with the full build and I'm not crystal clear on all the use cases for "getNextHeadingLevel()", but I hope that helps.

**Comment by terrill** [comment]
Excellent! Thanks @jessehall3! I'll keep an eye on this as it gets implemented in a wider variety of websites but it seems to do the trick. Implemented in 7fe68d63b4c3b46fb479e74fb2b2c9f5e5027f91
