### ISSUE TITLE
Use SVG instead of font icons

### ISSUE THREAD

**Issue by robfentress** [ableplayer/ableplayer#203]
The use of font icons for the buttons is problematic, since users who replace fonts for enhanced readability will not be presented with the hidden text that is designed to serve as an alternative.  Use of SVG for icons may be preferable or use the techniques described at: 
[Bulletproof Accessible Icon Fonts](https://www.filamentgroup.com/lab/bulletproof_icon_fonts.html)

**Comment by terrill** [comment]
@robfentress we opted not to use SVG because IE and Android were both slow to support it. IE in particular didn't have support until IE9, and even today (in IE11) SVG doesn't scale properly without CSS hacks. Instead, we're checking to see if the user has replaced the icomoon font, and if so, delivering images instead of fonts. The font checking occurs in initialize.js > setIconType(). We tested this widely when we first implemented it, but it's been a while. If you know this method to be failing in some circumstances, please let us know the details. 

All that said, it might indeed be time to revisit this approach as the number of IE8 users gets increasingly tiny. Thanks for link to the "Bulletproof" article - that will likely have some good ideas moving forward.

**Comment by robfentress** [comment]
@terrill I noticed the issue by using [Font Changer Chrome extension](https://chrome.google.com/webstore/detail/font-changer-with-google/jgjhhoglgjdklldfgoffdiaceffijeke?hl=en).  Loading the [Able Player Test #4 page](http://ableplayer.github.io/ableplayer/tests/test4.html), while a different font was loaded resulted in icons being replaced with placeholder glyphs as shown in the picture below:
![screen shot 2016-04-14 at 9 42 02 am](https://cloud.githubusercontent.com/assets/9356499/14530051/36ab7c92-0225-11e6-8c94-5c9c65a5eab1.png)

Awesome tool by the way!  Best I've seen so far.

**Comment by terrill** [comment]
Interesting - thanks. I'll have a look at that.

**Comment by robfentress** [comment]
As an aside, I don't encounter this issue when I use the Font Changer extension and look at the [demo page](http://filamentgroup.github.io/a-font-garde/markup.html) for the [A Font Garde library](https://github.com/filamentgroup/a-font-garde).  This is the library Filament Group provides that is based on their bulletproof technique.

**Comment by terrill** [comment]
With a2350045223dec834b657cd2ec2419d18b06c8f1 this now works correctly with Font Changer Chrome Extension. It **doesn't** work if the user changes their fonts after the page has loaded. It only checks for icon font support when the player initializes. In order to handle font changes on the fly, I'd have to add an event listener, but I'm not sure which events are reliably triggered when the font family is changed. I played around a little bit with this but didn't get anywhere. Meanwhile, if a user changes the font on the fly and their buttons disappear, they'll need to refresh the browser to rebuild the player with images. This isn't perfect, but I suspect it's a rare use case. 

Another problem is that the current technique (using getComputedStyle to check whether the default font-family for buttons has been overridden) doesn't work in IE (any version) if the user has "ignore font styles on web pages" checked. In that case, IE still reports the icon font as the calculated font for buttons; it just ignores it. I haven't found a way to test whether that checkbox is checked. 

So ultimately, I agree that switching to SVG may be a better solution. We would still need to provide our current image fallback for browsers that don't support SVG, but we're already setup to provide that fallback so it wouldn't be a big deal.

**Comment by terrill** [comment]
Added early support for SVG icons in b02dbd9b82c3e592e7b03e625396be0c48da7533
If you're curious you can enable SVG with data-icon-type="svg" 
However, it's not fully functional yet and will need to be thoroughly tested before it's ready for real world use.

**Comment by terrill** [comment]
Added support for SVG icons in 3fc6c100a551f0509922425fe9644e62c41c4ab4. 

There are various ways of approaching this, and each method has its own set of challenges for getting buttons with nested SVG to be accessible in all screen reader/browser combinations, and with proper visible focus. I consulted a variety of resources and tried various methods, and ultimately found this to work best: 

```
<button type="button" aria-label="Play">
  <svg viewBox="[viewBox data]" focusable="false" aria-hidden="true">
    <path d="[path data]"></path>
  </svg>
</button>

```
## Test Results: 
- VoiceOver in Safari 11.0.3 (MacOS 10.12.6): "Play button" 
- Voiveover in Safari (iOS 11.2.1): "Play button" 
- JAWS 2018 in IE11 (tabbing or reading): "Play button" 
- JAWS in Firefox (tabbing or reading): "Play button" 
- JAWS in Chrome 64 (tabbing or reading): "Play button"
- NVDA 2017.4 in Chrome (tabbing): "Play button play" 
- NVDA in Chrome (reading): "Button play" 
- NVDA in IE11 (tabbing): "Play button" 
- NVDA in IE11 (reading): "Button play" 
- NVDA in Firefox 58 (tabbing): "Play button" 
- NVDA in Firefox (reading), "Button play" 
- Narrator in Edge 41 (Windows 10, tabbing), "Play button"
- Talkback on Android 4.4.2 (Nexus 4): "Play button" 

I'm considering making SVG the default icon type. However, currently we're testing for browser support of icon fonts, and falling back to `<img>` elements if tests fail. I would want to build in a similar test and fallback for browsers that don't support `<svg>` elements.

**Comment by terrill** [comment]
SVG is now the default for icons as of 32be4ead6fdcbf19930b32da09b0fe91d481ccd3
If browsers don't support SVG, it falls back to icon fonts unless those aren't supported or are overwritten by a custom style sheet, in which case it defaults to images. The default can be changed by the author with the **data-icon-type** attribute.
