### ISSUE TITLE
Question: Can you have both lyrics mode and transcript in a single VTT?

### ISSUE THREAD

**Issue by mrdwab** [ableplayer/ableplayer#206]
What would be the recommended way to have both lyrics and a transcript in a VTT file? 

The desired display for the transcript would be to have the normal dialogue displayed as a transcript, but when the narrator gets to verse, the transcript should be shown with each line of the poem on its own line.

**Comment by terrill** [comment]
@mrdwab this is a great question! Unfortunately I can't think of a way to make it work. Able Player honors line breaks in the WebVTT file when the contents are displayed as captions, but when it displays them as a transcript it consolidates the contents into longer blocks of text unless data-lyrics-mode is true, in which case it doesn't. So the different handling of content (regular mode vs lyrics mode) is defined for each transcript as a whole, not for individual sections within a transcript. 

One possible approach, that will require additional Able Player development, would be to create your own transcript, formatted as you see fit. To make it interactive you would need to add markup that Able Player would recognize. I could add support for a new attribute **data-able-transcript** which, combined with **data-player="*id_of_media_element*"** would allow the Able Player instance to absorb the transcript and interact with it. 

There's already a need for this sort of functionality since sometimes Able Player's automatic transcript generation doesn't result in a transcript that has the optimal structure. How urgently do you need this?

**Comment by mrdwab** [comment]
@terrill Thanks for the response. I'm honestly still in the prototyping phase, looking at different options for interactive transcripts. For the *materials* I am working with, the urgency is high, but for the *project* I'm working on, we don't have a very clear timeline yet :-) 

In looking at the different options I've come across so far, I am happiest with Able Player because it requires the least amount of additional work if I already have a valid WebVTT file. 

For the possible approach you mention, would that be to create my own `span`s with the data start time and so on and then just mark-up the paragraphs as I want them displayed in the transcript? That's what I've used with [one of the other options](https://github.com/pipwerks/EasyCaptions) that I explored, inserting `<p>` and `<br>` tags as required, but I really like the feature set of Able Player, especially the accessibility options. So, I guess that an integration like you describe would still be a very nice feature to be added.

**Comment by terrill** [comment]
This is now possible as of bcdc474f119fc6d5977f1f18822ee80cbf7fca55

You can manually code a transcript then reference its id in the **data-transcript-src** attribute. Instructions for how to code the transcript are included in the ReadMe in the develop branch
