### ISSUE TITLE
Italics in ableplayer

### ISSUE THREAD

**Issue by Quasar33** [ableplayer/ableplayer#209]
Two related questions:

1) Does anyone know when or if the italics commands <i> and </i> will work in Ableplayer? 

2) Until such time as italics do work, could the ableplayer javascript be revised to remove that tag from vtt files?  My Swift software makes it very labor-intensive to remove italics and there's no way to exclude automatically them from a vtt export.  Right now, I'd have to create a brand-new Swift file and manually remove each block of italicized captions.

Thanks,
Brian

**Comment by Quasar33** [comment]
Well, the italics commands don't even show up in my questions. `<i>` and `</i>`

**Comment by terrill** [comment]
@Quasar33 this was discussed in https://github.com/ableplayer/ableplayer/issues/193 - that issue was closed as it's part of the larger issue to more fully support the WebVTT spec ( #13 ). 

I'll leave this one open though since there seems to be a demand specifically for `<i>`. As an interim step toward full WebVTT support I'll try to look sometime soon into supporting `<i>`, `<b>`, and `<u>`, and possibly `<c>` (class). It's a busy week though, which includes a few other top priority Able Player enhancements, so give me a couple weeks.

**Comment by Quasar33** [comment]
Thanks, Terrill.

Just FYI: I'm a freelance captioner who's currently using Swift Create 8
software to export vtt files.  I created a php code to remove the italics
from my own Swift vtt exports.  It looks like there might be similar
problems with exporting musical notes and colors from Swift for
Ableplayer.

Brian





On Mon, Apr 25, 2016 at 11:28 AM, Terrill Thompson <notifications@github.com

**Comment by terrill** [comment]
@Quasar33 can you attach an example of one or two Swift-generated WebVTT files that include those sorts of features?

**Comment by Quasar33** [comment]
The attached VTT file has colors, italics, music notes, and a transparent
space that causes me trouble when I'm adding the VTT file to a mySQL
database.

Also, the "line" values are exported as 52.66%.  I thought they should be
100%, since the captions in Swift are bottom center.

Thanks. Hope this helps.

**Comment by Quasar33** [comment]
Here's one more version: this is exported with "compatibility mode off."

**Comment by terrill** [comment]
Support for <i> and <b> has been added for both captions and transcripts in 0e28ea2b03db2b35e8d9d0c592f8af58428c18e1
