### ISSUE TITLE
Two implementation questions from a newbie

### ISSUE THREAD

**Issue by Quasar33** [ableplayer/ableplayer#215]
I'm not sure if these kinds of beginner questions are appropriate for this forum, but I've found no other place online where I can ask such things about ableplayer.  If there is a better place for me to go, please let me know.

Meanwhile, can someone please tell me:

1) how to stop the "auto scroll checkbox" and the "language" dropdown menu from appearing above my interactive transcripts?  
2) how to keep the original aspect ratio of my videos. (Every video in ableplayer seems to play back in the same boxy shape, despite its wide-screen appearance in YouTube, for instance.)

Thanks.

**Comment by terrill** [comment]
First, try the latest build on the develop branch: https://github.com/ableplayer/ableplayer/tree/develop
That has a more responsive player wrapper. 
For YouTube videos, there are two options for setting the default width and height: 
1. Use the width and height attributes on the <video> element. 
2. Let Able Player retrieve that information from YouTube. It takes a couple seconds to get that information from the YouTube Data API so it's a little clunky (the player resizes after loading), but at least your video should play in the right resolution. 

Regarding the "language" dropdown in the transcript toolbar, that should only appear if you have multiple languages (i.e., captions and subtitles). If you do, I would argue that this is an important feature and shouldn't be removed. If there's only one language though and you're still seeing a dropdown, I suspect you're using an older version. 
 
Regarding the "auto scroll checkbox", that's a necessary feature of the transcript. If the transcript  requires scrolling, you have two situations: 
1. Auto-scroll is on. As content in the transcript is highlighted, the transcript scrolls up to keep the highlighted text viewable. Since the player is auto-scrolling though, this makes it cumbersome to scroll manually (i.e., you scroll down to read ahead, and the player scrolls back up again). 
2. Auto-scroll is off. The player doesn't auto-scroll as it highlights. This allows the user to scroll freely and read parts of the transcript that aren't otherwise visible. The down side of this mode is that no scrolling happens as the player highlights text, so if the user doesn't manually scroll the highlights eventually leave the visible area. 

Since both of these modes are necessary depending on a user's current needs, there needs to be a convenient checkbox so users can easily switch between modes. 

The only case in which this checkbox would not be necessarily is if the transcript requires no scrolling at all, i.e., the entire transcript fits in the visible container. I'm not sure how to test for that but I suspect it's possible. If so I could remove the checkbox if no scrolling is required. But Able Player currently doesn't do that.

**Comment by terrill** [comment]
The above recommendations now apply to the latest release on the master branch as well (version 3.0).
