### ISSUE TITLE
JW 7?

### ISSUE THREAD

**Issue by rebelaide** [ableplayer/ableplayer#238]
Hello,

Are there plans to support JW 7 instead of 6? 

Thanks,

John

**Comment by terrill** [comment]
@rebelaide I personally have no plans to do further work on JW Player support. Since JW Player is intended to serve as a fallback player for browsers that don't support HTML5 media, I think we have less and less of a need for this as we get further away from IE8.  

That said, it's an open source project so if others want to work on updating JW support they're welcome to do that. On the other hand, if the need is not driven by IE8 support, but for encrypted media support, I would rather see the community's efforts going into supporting W3C Encrypted Media Extensions: #199

**Comment by rebelaide** [comment]
Thanks @terrill . The reason why I ask is because of fallback for youtube support. JW 7 will play unlisted videos when ableplayer will not.

**Comment by terrill** [comment]
@rebelaide I know you closed this issue but just to clarify - Able Player *does* support **unlisted** videos. You just have to know the video's URL, then you can plug its YouTube ID into the *data-youtube-id* attribute.  It doesn't support **private** videos.

**Comment by rebelaide** [comment]
@terrill Thanks Terrill. If a video is unlisted, will it still load or do we have to make code changes?

 We are working on integrating ableplayer with Canvas right now. Hitting some snags with our custom JS file and pointing to the image icons. Have you had any luck?

**Comment by terrill** [comment]
@rebelaide there is no difference in how published and unlisted videos are supported. The only difference is that YouTube doesn't promote the URL of unlisted videos, but once you have the URL they're the same.  

I haven't tried integrating Able Player into Canvas. That's on my todo list though so keep me posted if you make progress. I created an issue so we can track that separately: #244
