### ISSUE TITLE
Question about insanely high z-index

### ISSUE THREAD

**Issue by btopro** [ableplayer/ableplayer#240]
Is there a reason that ableplayer has crazy high z-index settings? I'm trying to integrate it as part of a UI I'm working on and wanting to know if I need to make a sticky-mobile pervasive bar 10000 z-index to safely account for it or if there's a rationale behind the high z-indexes.

Thanks

**Comment by terrill** [comment]
@btopro which version of Able Player are you using?  There's a function in control.js  named getHighestZIndex() which was once used to assign a z-index value that was slightly higher than the highest z-index on the page in order to ensure key elements (e.g., dialogs, pop-up windows) were on top. It quickly became apparent though that this was a bad idea as we get caught up in z-index wars with other scripts. So that function is no longer called, and z-index values should cap out at the highest value specified in [ableplayer.css](https://github.com/ableplayer/ableplayer/blob/v3.0/styles/ableplayer.css). 

If you're seeing this issue with a recent version of Able Player, there might be a bug. Is there a public URL where I can check out your site?

**Comment by btopro** [comment]
3.x. Not really a bug, I was just curious if there was any kind of rationale behind it. I adjusted my implementation's CSS to take it into account so I could keep the ableplayer.css file pure :) thanks for answering so quickly
