### ISSUE TITLE
Youtube Playlist

### ISSUE THREAD

**Issue by gama41** [ableplayer/ableplayer#249]
Hello, 

I want to add subtitles to a custom playlist of youtube videos and maybe some mp4 videos. I try `<li      data-youtube="dzPOk8yVgPY">` to copy the example of `<li data-mp4="title.mp4">`.
But it's not working, it's because it's not possible to make a playlist with youtube videos or it's not the correct way to do it ?

**Comment by terrill** [comment]
Overall playlist support is not currently very good. See Issue #157 for additional information. In particular note that most recent comment: This issue has moved to a W3C Community Group so we can identify a _somewhat_ standard means of supporting HTML5 media playlists, since no standard currently exists.

**Comment by terrill** [comment]
Playlist support is now much-improved as of c0d291c70fd5b8be5879c6fef362407c699c17c3
