### ISSUE TITLE
YouTube timedtext for Captions

### ISSUE THREAD

**Issue by brunetgarcia** [ableplayer/ableplayer#251]
Not sure if this has been explored already, but, aside from not being in the v3 API, what would be drawbacks to using (https://www.youtube.com/api/timedtext?type=list&v=tnsB6YCHVXA) or (https://video.google.com/timedtext?type=list&v=tnsB6YCHVXA) to get the captions list and then use the language code and name from the list to get the VTT file from
(https://www.youtube.com/api/timedtext?fmt=vtt&v=tnsB6YCHVXA&lang=en&name=English)?

**Comment by terrill** [comment]
@brunetgarcia Is this method for retrieving the caption file documented anywhere? My biggest concern is that Google might remove this at any moment, especially if it's an unofficial undocumented feature. Otherwise it does seem to work, so maybe we could implement it with a "use at your own risk" warning. 

Also, note that the name parameter doesn't seem to be necessary when retrieving the VTT file, only lang: 
https://www.youtube.com/api/timedtext?fmt=vtt&v=dhwpLACAls8&lang=es

**Comment by brunetgarcia** [comment]
I have not seen any official documentation, but I do see that it has been in use for [several years](http://webapps.stackexchange.com/questions/2751/downloading-auto-generated-youtube-transcriptions).

It seems that some videos do not require the track name but some do.
For example, this works
https://www.youtube.com/api/timedtext?fmt=vtt&v=tnsB6YCHVXA&lang=en&name=English
but this does not
https://www.youtube.com/api/timedtext?fmt=vtt&v=tnsB6YCHVXA&lang=en

**Comment by flintforge** [comment]
@brunetgarcia 
You can figure out why by takin a look at the list
https://www.youtube.com/api/timedtext?type=list&v=tnsB6YCHVXA

**Comment by terrill** [comment]
Full support for YouTube captions has been added as of 5d6ba414d9a0406895a1d21681fcdb2a24836052 using the timedtext API. I still have concerns about its lack of official documentation, but it works for now! Thanks everyone for the tips, and sorry it took so long to follow up on this.
