### ISSUE TITLE
Inconsistent language selection behavior between captions and transcript

### ISSUE THREAD

**Issue by mhamaoka** [ableplayer/ableplayer#256]
If you select a language for closed captions, the transcript language also changes to the language you selected. But if you select a language in the transcript, the caption language doesn't change.

This behavior is observable in the Able Player Video Demo 6 on the Able Player Examples page.

REPRODUCE: Start playing with captions in English. Switch the CC language to Spanish and the transcript will also show Spanish text. Now, use the drop-down in the transcript to switch back to English and the transcript will show English, but the player will still be showing Spanish captions.

**Comment by terrill** [comment]
@mhamaoka This is actually the intentional behavior after much discussion. The issue is that users have two competing needs when it comes to language of captions and transcript: 

1. Most users will likely want the captions and transcript to be in the same language. 
2. Some users have expressed a desire to have the captions and transcript in different languages. Use case: they're learning the spoken language of the video, and want to see captions in the spoken language, but also want to see the translated text in their native language in the transcript. 

If we always keep the languages in sync by changing both the captions and transcript, it would be impossible to meet the needs of the second group of users. So, we decided to offer two ways of changing the language:

1. Change the caption language - this also changes the transcript language so the languages are in sync. This meets the needs of the first group of users.  
2. Change the transcript language - this only changes the transcript language, thereby allowing the second group of users to have the captions and transcript in different languages.  

Admittedly that's a bit confusing, but we couldn't think of a better way to handle this without requiring more steps for users.

**Comment by mhamaoka** [comment]
Thank you for the explanation.
