### ISSUE TITLE
Can not play on iPhone/iPad (Android ok) - keep buffering and then not responding

### ISSUE THREAD

**Issue by webguyzz** [ableplayer/ableplayer#264]
Please help us finding the cause. We have used the same code elsewhere and they were working just fine.

Try player on: www.hadley.edu/FCE-NVC.asp

Code used:

```
<video id="video1" preload="auto" width="480" height="320" poster="upload/2016-Blast-Conference.jpg" data-able-player data-show-now-playing="false" data-use-transcript-button="false" data-include-transcript="false">
    <source type="video/mp4" src="http://hwcdn.net/k4w2w6y8/cds/media/2016-Blast-Conference_FCE_NVC_WINNER.mp4"/>
    <track kind="captions" src="upload/2016-Blast-Conference.vtt"/>
</video>
```

Thanks!

**Comment by terrill** [comment]
@webguyzz that doesn't seem to be working in desktop browsers either - I just tried with both Firefox 51.0.1 and Chrome 55.x in MacOS Sierra 10.12.2, and in both browsers the video just buffers endlessly. Part of the problem might be that your web page has an XHTML Transitional doctype (and fails validation). Since Able Player is built to work with HTML5, try changing the doctype and be sure the page validates. Does that fix the problem?

**Comment by webguyzz** [comment]
Thanks! I just updated the file to use purely HTML5 doctype. It is still experiencing the same issue...please assist.

**Comment by terrill** [comment]
Looks like you're using an older version of Able Player (2.3.86).  The most recent stable release is 3.0. So the next step in troubleshooting would be to upgrade: https://github.com/ableplayer/ableplayer/releases/tag/v3.0

**Comment by webguyzz** [comment]
After the upgrade, it seems like the issue is still there. Did we miss anything? Thanks!

**Comment by terrill** [comment]
Have you tried playing the video in the browser's native media player? You can do that by simply removing the **data-able-player** attribute from the `<video>` element. If it plays fine in browsers' native players, then it's an Able Player problem. Otherwise it's some other problem, perhaps with the encoding of the video itself.

**Comment by terrill** [comment]
I'm closing this issue since it wasn't an Able Player issue. As for encoding references, there are lots of good resources available if you search for something like "encoding for HTML5 video".
