### ISSUE TITLE
Youtube playback in AblePlayer no longer sizing correctly and can't play full screen

### ISSUE THREAD

**Issue by sprousecu** [ableplayer/ableplayer#283]
Recently YouTube videos started appearing very small and left-justified (only about 350px wide) in AblePlayer.   I notice this is the case in your sample video (http://ableplayer.github.io/ableplayer/demos/youtube.html) as well. Any idea what can be done to address this?

**Comment by terrill** [comment]
If you provide width and height attributes on <video> the video will be sized properly. However, without these attributes we previously were able to get width and height via the YouTube API. The data returned by YouTube changed sometime in early 2017, resulting in the small video.  This has been fixed in 8643e03ddbb9a4860289f7db43c429310506bddf

YouTube video dimensions in full screen mode seems to be a different problem. Working on that next...

**Comment by terrill** [comment]
YouTube full screen sizing bugs fixed in 45c841b1446ba0f7bea9c7d9c81ded0a17e6040c

**Comment by bdrafta** [comment]
It looks like this wasn't merged to main. The new code fixes the issue in my test.

**Comment by terrill** [comment]
Thanks for the feedback @bdrafta .  Lots of fixes upcoming in February; master will be updated once those are complete.
