### ISSUE TITLE
Add support for disabling captions by default

### ISSUE THREAD

**Issue by btopro** [ableplayer/ableplayer#292]
In cases where you have the captions and transcripts on it's a little overkill to be doing both by default / forcing a user action in order to disable by default via cookie after the fact.

There are options via data attributes for other properties. this would be eas enough to pass in via `data-captions` in order to disable it by default via `off` or osmething like that.

**Comment by terrill** [comment]
@btopro Sorry for the slow reply. We decided early on in Able Player to have captions on by default because some users *need* to have them on, whereas others *prefer* to have them off. We decided one user's need should take precedence over another user's preference.  Also, there's a lot of evidence out there that captions have many benefits beyond just accessibility (e.g., I've seen data from both Facebook and Yahoo that attests to a much higher level of engagement with video if it's captioned).  

Also, a transcript isn't a substitute for captions unless it's positioned immediately beneath the video and auto-scrolls with the current text always at the top (Able Player's default transcript doesn't do that; its auto-scroll keeps text positioned in the middle of the container). Users who depend on captions need the text to be within the same field of vision as the video; otherwise they have to look back and forth between the video and text, which is burdensome and can cause them to miss important content.  So, in most contexts having a transcript meets different needs than having captions, and one shouldn't be dependent on the other.

**Comment by btopro** [comment]
no problem, seems a bit overwhelming :) and all understood. I'll close this out.

**Comment by lukepass** [comment]
Hello, I had the same problem and I solved it with the following custom code:

```
// clicks on the last `li` of the `ul` with id `video1-captions-menu`
const captionsMenu = document.getElementById('video1-captions-menu');

if (captionsMenu) {
  const lastLi = captionsMenu.lastElementChild;

  if (lastLi) {
    lastLi.click();
  }
}
```

You can add this code to the `loadedmetadata` event:

```
video.addEventListener('loadedmetadata', () => {
    //
});
```

**Comment by lukepass** [comment]
Another possible working solution:

```
    document.cookie = 'Able-Player=' + JSON.stringify({
      preferences: {
        prefCaptions: 0,
      },
    });
```
