### ISSUE TITLE
Issue with Video Play button on Chrome only when JAWS running

### ISSUE THREAD

**Issue by ctataryn** [ableplayer/ableplayer#318]
**Steps to reproduce** (not sure if VM setup has anything to do with the problem, but included the steps nonetheless)

* Download and install [Oracle Virtual Box](https://www.virtualbox.org/wiki/Downloads)
* Download the [IE11 Virtual Box Image](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)
* Import the .ova file in Oracle Virtual Box via `File->Import Application`
* In Virtual Box, for this machine (before turning it on) adjust the setting: `Machine -> Settings -> Audio ` and make sure both input/output are checked
* Start the VM
* Inside the VM
   * Download and install [JAWS 32bit version for Windows](https://www.freedomscientific.com/Downloads/JAWS)
   * Download and [install Git](https://git-scm.com/)
   * Install IIS
      * `Control Panel -> Programs -> Turn Windows feature on or off -> `check: `Internet Information Services`
      * Under `Start menu -> Programs -> Administrative Tools -> Internet Information Services (ISS)`
      * Navigate to: `Sites -> Default Web Site -> MIME Types`
      * Add:  `mp4 -> video/mpeg`  and   `vtt -> text/vtt`
   * Open GitBash
      * cd C:\inetpub\wwroot
      * git clone https://github.com/ableplayer/ableplayer.git
   * Open Google Chrome
   * Navigate to: http://localhost/ableplayer/demos/index.html
      * Make sure JAWS is running
      * Pick any of the `Video Examples`
      * Tab around the page until you get to the Play button
      * Press enter or spacebar and notice you only hear a "bleep-bloop" and nothing happens
      * Quit the JAWS application and tab to the Play button. It now works as expected.

Work Around (with JAWS running)
* Tab to the play button
* Press enter, you will hear "Group box"
* Press Tab, notice the re-play button is highlighted
* Press left-arrow, announcement will be "p"
* Press Enter, the video will play
* Press Tab, notice the re-play button is highlighted
* Press left-arrow, announcement will be "a"
* Press Enter, the video will play

Firefox and IE work fine

**Comment by ctataryn** [comment]
@terrill ☝️ My attempt at a fix.  I'm not sure how dangerous using `role="application"` is, so I'll defer to your better judgement. Maybe it'd work if the button's had `role="button"` instead?

Placing the `role="application"` on just the `able-left-controls` div worked great in Chrome/IE, however for Firefox the behviour was that you'd need to either exclusively use spacebar, or you'd have to tap enter twice on the controls.  Adding `role="application"` to both the `able-left-controls` div and the buttons solved the issue in Firefox.

**Comment by terrill** [comment]
@ctataryn thanks for taking this on. I don't think `role="application"` is the right solution though. Since that role has such a significant effect on how screen readers operate, it really needs to be used only in rare occasions where the UI truly is a self-contained application with its own keyboard model (think Google Docs). 

Able Player's buttons are just buttons, so they should be accessible without resorting to such extremes. I can replicate the problem with JAWS 2018 64-bit in Chrome, not using a VM, so I think we can generalize to this being an issue with JAWS in Chrome.  Here are some additional observations: 

- When navigating with tab, JAWS in Chrome announces the Play button as "Play group box" rather than "Play button".  All other buttons are announced as buttons. 
- When navigating with "B" (to jump to the next button) using JAWS in Chrome, the Play button receives focus, but is announced as "Group box". All other buttons are announced as buttons. 
- When navigating with arrow keys, JAWS in Chrome has issues with several buttons, not just Play. The button that is highlighted with the JAWS focus indicator is sometimes **not** the button that's announced (e.g., it says "Play" but the Restart button has visible focus). When this happens, the button with visible focus - **not** the one that's announced - is the one that actually has focus and is triggered if the user presses spacebar. 
- JAWS does not exhibit any of these problems in any other browser. I tested with Firefox, IE11, and Edge. 
- NVDA does not exhibit any of these problems in Chrome. 
- ChromeVox does not exhibit any of these problems in Chrome. 

I carefully reviewed the DOM in Chrome DevTools, and don't see any difference between the Play button and other buttons. 

I tested with both `data-icon-type="font"` and `data-icon-type="image"` to see if the problem occurs only when `data-icon-type="svg"` (the default). The problem occurs with all three, so it's not an SVG issue. 

Using [AViewer,](https://github.com/ThePacielloGroup/aviewer) I compared the data that Chrome is exposing via all accessibility APIs for the Play button vs the Restart button. I see no difference at all between the two. I've attached a screen shot of the aViewer info for the Play button, which to my eye shows nothing extraordinary that should result in JAWS misinterpreting the button as a group box (sorry, I don't have an accessible version). 

Given all this, I'm inclined to dismiss this as a JAWS bug in Chrome. I extracted the `<div class="able-left-controls">` element, along with everything inside it including the Play button, and created a test page that just contains that element. JAWS handled this just fine in Chrome, so there's something else within Able Player that's throwing JAWS off. Finding the culprit would require a lot more debugging, more than I have the time for in the near future.

**Comment by ctataryn** [comment]
@terrill I felt much the same about the `application` role, it's a hack.  We had a similar problem with NVDA with the following structure:

```
<ul>
   <li><div>....</div>
   <li><div>....</div>
   .
   .
   .
</ul>
```
The first element was virtually invisible to the screen reader.  We then wrapped the <div>s in a <span> within the <li> and it then worked as expected.

I had tried the same for this PR before resorting to `role="application"` but to no avail.  I'll keep plugging away though and see if I can find the magic combination that works.

**Comment by terrill** [comment]
@ctataryn I realize this is an old issue. Whatever the problem was, I think it's been fixed (JAWS, Chrome, and Able Player have all been updated since you logged this issue). I'm not able to replicate the problem using JAWS 2020 in Chrome 80.x in Windows 10. I'm not using a VM, so not attempting to replicate your setup exactly.  

I'm closing this issue, assuming all is well. If you continue to experience the problem though, feel free to reopen it.
