### ISSUE TITLE
Hover and focus colors

### ISSUE THREAD

**Issue by mnciao** [ableplayer/ableplayer#342]
Terrill,
When playing with your demos, I noted that the button outline on hover is green, but when using tab focus, it's a sort of yellow.
Is this intentional? If so, can you provide the rationale?
Thanks,
Jay

**Comment by terrill** [comment]
@mnciao :hover and :focus are stylized differently because they're communicating different information. If someone uses both keyboard and mouse, it's arguably helpful to be able to easily spot the focus or location of each of these tools. 

I don't feel super strongly about this though. I'm open to counter-arguments if anyone feels this creates usability problems.

**Comment by mnciao** [comment]
Is it easy enough to change the colors for our own use? I am not familiar with the code and don't want our developers wasting time if it may cause issues.

**Comment by terrill** [comment]
Yes, it's just CSS. Look for the **outline-color** properties in **styles/ableplayer.css**.

**Comment by mnciao** [comment]
What I suspected. Thanks!
