### ISSUE TITLE
Fullscreen fails when multiple YouTube videos appear on same page

### ISSUE THREAD

**Issue by tqureshi-uog** [ableplayer/ableplayer#349]
This is a serious bug I've just run into, and I could've sworn it didn't happen before - perhaps a recent change to the way Able Player handles YouTube caused it? Steps to reproduce are:

1. Add more than one YouTube video to a single page
2. Click the fullscreen button on one of the videos
3. Hit escape or the fullscreen icon to go back to normal mode
4. The video you were watching goes back to normal size, but all the other videos on the page become huge, as if they've taken on the fullscreen video dimensions instead:

![image](https://user-images.githubusercontent.com/13698158/49251884-8bebff00-f3f0-11e8-890d-39aaffe204a6.png)

Note that I created the above test page from https://ableplayer.github.io/ableplayer/demos/youtube.html - I didn't change anything except the IDs for the first two videos (since the ones on the original page won't load). 

Any idea why this is happening and if there's something we can do to prevent it?

**Comment by terrill** [comment]
@tqureshi-uog it turns out this has always been a problem, and it isn't unique to YouTube videos. Any time there was more than one instance of Able Player on a page, requesting full screen for any one of those players had an unintended effect on the other players. Then, after exiting full screen mode the player that had been full screen was restored to its original size but the other players weren't. 

This is now fixed in cd3c7e0df2430a659deb6d4600b3074c0ed34096
