### ISSUE TITLE
Add support for keyboard shortcuts within form fields

### ISSUE THREAD

**Issue by terrill** [ableplayer/ableplayer#362]
Currently, Able Player only handles keydown events if the user's focus isn't in a form field. I've just learned of a use case though where it would be desirable to handle keydown events within a form field: A transcription application, where the user is transcribing audio into a textarea, and needs to toggle play/pause, or rewind/forward the media on the fly while they're transcribing. 

I'm envisioning two possible ways of Implementing this: 

**Approach 1**
- If the keydown event is accompanied by Ctrl and/or Alt, handle it as an Able Player shortcut, even if the user is in a form field.  This approach would be simple to implement, but might result in users more easily triggering a hotkey function _accidentally_ . 

**Approach 2**
- Same as above, but only if the attribute _data-mode="steno"_ is present, to ensure this is an application where hotkeys are expected within form fields. 
- In "steno mode", user preferences for modifier keys would be ignored (i.e., Ctrl + Alt + letter) would be expected, even if user preference is for hotkeys without modifier keys.  
- In "steno mode", support for hotkeys within form fields could be limited to textarea fields, since there might be other fields on the page where hotkey support is unlikely to be necessary, and accidentally triggering a hotkey function is likely to be undesirable.

**Comment by ossossosso** [comment]
Thanks Terrill for your reply.

I'm a visually impaired transcriber.

It would be interesting to use Able Player in addition to a Typing Tutor web application.

Mainly a Typing Tutor application is done by an Edit Field form where you transcribe text that appears on the screen. In my case I need to listen a speaker instead of reading, so would be useful to control audio in the meantime I'm typing into the Edit Field.

Usually keyboard shortcuts to control a player are linked to a usb foot pedal to control it better.

For a transcriber the main features are:
- Play/Pause

- Stop

- Skip Forward/Backwward 2 sec (if you are typing slower for a while or you didn't understood a word, you don't need to skip back 15-20 seconds, it's too much, because the final target is to finish as fast as possible to type the text of the exercise/lesson)

The best situation is to have ability to customize keyboard shortcut for the features above.
Usually a transcriber to type really fast needs additional applications which help to insert pieces of text. To access these applications the only way is to use keyboard shortcuts.

So to avoid possible conflicts would be great to customize as much as possible.
You know, the player needs shortcuts, Word Processor applications need shortcuts, the Web Broser needs shortcuts, the Screen Reader needs shortcutss.
After water, love and holidays, also shortcuts are scarce in the world.

Sometimes I wonder how Aliens can be so advanced with only four fingers per hand.
Probalby they use something like Google Home.

Thanks for this project.
Really cool!

Daniele.

**Comment by ossossosso** [comment]
Hi Mr. Thomas,
I'd like to know if this feature can be stilll considered for future updates to the player.

Thanks a lot.

Daniele.

**Comment by terrill** [comment]
@ossossosso I can easily add data-mode="steno", which would enable users to control the player with hotkeys even while typing in a textarea field on the same page.  That won't allow for full customization of the hotkey combination, but users can already control the modifier keys via the Keyboard Settings dialog.  I'll escalate this and add data-mode="steno" to the next minor release. Hopefully I can work on that sometime over the next couple of weeks.

**Comment by terrill** [comment]
I added **data-steno-mode** in f5e887fb8788d8a4a714acd532678ca56ebe6d22

Simply add **data-steno-mode** to the `<audio>` or `<video>` element. Then, the player can be operated using keyboard shortcuts from within a textarea field on the same page. 

I also created a demo page that features an [Audio Transcription Example](demos/audio9.html).

**Comment by ossossosso** [comment]
Wow, this is a great news.

Can I ask you a small step by step guide on how to use this feature?

At the moment I'm using the player through the Wordpress plugin:
"An implementation of Able Player for WordPress Versione 1.0 | Di Damion Armentrout".

If I try to open the "demo page" I receive "Page not found".

Thanks a lot!

**Comment by terrill** [comment]
@ossossosso you should use the official [Able Player Wordpress plugin](https://wordpress.org/plugins/ableplayer/). The version you're using is unofficial, and to my knowledge is no longer actively maintained.  

The new "Steno Mode" feature is currently only available on the develop branch. I have a few more updates to make, then sometime in the next two weeks I'll release a new version of Able Player, and soon thereafter I'll update the Wordpress plugin so it's using the new version of Able Player. 

Once the updated Wordpress plugin is released, you'll be able to add **data-steno-mode** to the `<audio>` or `<video>` element within your Wordpress page. Assuming your page also includes a `<textarea>` field for entering a transcript, all Able Player keyboard shortcuts will work as you're typing within that  `<textarea>` field. If you encounter snags as you're trying to implement this, let me know.

**Comment by ossossosso** [comment]
Ok, perfect.

I'll check the Wordpress Plugin Manager until I'll see the new version of the player available and I'll try it, I think it's the easiest way.
I'm not a developer, and without a guide I don't know how to test your code.

I'll let you know.

Thanks again.
See you soon.
