### ISSUE TITLE
Last track in audio playlist won't increment if data-prevnext-unit="playlist"

### ISSUE THREAD

**Issue by lardconcepts** [ableplayer/ableplayer#367]
Last track in audio playlist won't increment if data-prevnext-unit="playlist"

I was actually hoping that this would cause prev/next to act on playlist items, but while it still acts on time, if you're on the last playlist item, it just doesn't increment time.

**Comment by terrill** [comment]
@lardconcepts there is no **data-prevnext-unit** attribute. That attribute was proposed in the discussion surrounding issue #200 but never implemented. So if your audio playlist isn't advancing properly, there is probably some other problem. What do you mean exactly by "Last track in audio playlist won't increment"? 

From my observations, using [Able Player Audio Demo 2](https://github.com/ableplayer/ableplayer/blob/develop/demos/audio2.html) as an example: 

- That example includes the **loop** attribute on the `<audio>` element. Therefore, I expect it to automatically return to the top of the playlist and play the first track after the end of the last track. This works as expected. 
 - If I remove the **loop** attribute, I expect it to stop playing after the end of the last track. This too works as expected. 

Thanks for clarifying.

**Comment by lardconcepts** [comment]
Thanks, and thanks for your work on this great player.

The code I was referring to is in the first post of #366 found at
https://github.com/ableplayer/ableplayer/blob/master/build/ableplayer.js#L261

```
// Previous/Next buttons
		// valid values of data-prevnext-unit are 'playlist' and 'chapter'; will also accept 'chapters'
		if ($(media).data('prevnext-unit') === 'chapter' || $(media).data('prevnext-unit') === 'chapters') {
			this.prevNextUnit = 'chapter';
		}
		else if ($(media).data('prevnext-unit') === 'playlist') {
			this.prevNextUnit = 'playlist';
		}
		else {
			this.prevNextUnit = false;
		}
```

> What do you mean exactly by "Last track in audio playlist won't increment"?

Apologies, that was a bit unclear!

OK, if I have 10 tracks, all 3 minutes, if I click the "forward" button, it will jump forward by a percentage of time (or a fixed value, if I set it).
But if I add `data-prevnext-unit="playlist"`, then on that LAST track only, this doesn't work.

The reason for doing this, was to try and advance track playlists.

I also tried setting data-seek-interval="10000" which kind of works, but with a long track and slow internet, everything hangs while the media loads so it can seek to the end, before it plays the next track. Which is surprising as the server accepts byte-ranges.

I did find a hack that would use jQuery to "click" the next item in
the playlist after the active item, but of course, that brought focus
away from where the user thought they currently were.
I know I should be able to "talk to" AblePlayer via $(AblePlayer)[0]
and $(".able-playlist"), but I failed - I realise this has wandered into playlist territory again so I'll post there.

Thanks!

**Comment by terrill** [comment]
@lardconcepts thanks for clarifying. And I stand corrected about **data-prevnext-unit**!  I apparently had added that in anticipation of possibly supporting it, then forgot about it. Although *this.prevNextUnit* is defined in the code block you quoted, it's never actually used anywhere else in the code, and that attribute isn't formally documented. 

As discussed in #200, I will add new "Previous" and "Next" buttons to the controller if a playlist is present. The **data-prevnext-unit** will no longer be needed or supported, since the new Previous and Next buttons will always be for playlist navigation, and the rewind and forward buttons will always be for navigating within the current title.   

I'm closing this issue now. The problem you're describing should be addressed when the new buttons have been implemented.
