### ISSUE TITLE
Volume button not visible for `volume-soft`

### ISSUE THREAD

**Issue by karate** [ableplayer/ableplayer#368]
[`scripts/buildplayer.js`](https://github.com/ableplayer/ableplayer/blob/develop/scripts/buildplayer.js#L814) mentions:

> // volume buttons are: 'mute','volume-soft','volume-medium','volume-loud'

But in [`scripts/initialize.js`](https://github.com/ableplayer/ableplayer/blob/develop/scripts/initialize.js#L233) only `volume-medium` and `volume-loud` are taken into account.

I solved this by using the same icon as `volume-medium`. 
```
diff --git a/scripts/initialize.js b/scripts/initialize.js
index 6ff9bb2..2f027b0 100644
--- a/scripts/initialize.js
+++ b/scripts/initialize.js
@@ -231,6 +231,7 @@
                                break;
 
                        case 'volume-medium':
+                       case 'volume-soft':
                                svg[0] = '0 0 20 20';
                                svg[1] = 'M14.053 16.241c-0.24 0-
```
I'm not sure if this is appropriate. 
Please let me know if I should do a PR.

**Comment by terrill** [comment]
Thanks @karate ! This was actually a different problem in initialize.js - `volume-soft` was actually there among the support case values, but was erroneously identified as `volume-mute`. There was another error though in volume.js that was preventing the SVG icon from being swapped out at all as the volume changed. This has been fixed in 722f5363d232f53d2a314bde7cbeae4d2a14d5ff
