### ISSUE TITLE
Can the control bar of Able Player be customized?

### ISSUE THREAD

**Issue by katlamen** [ableplayer/ableplayer#382]
Hi All, 

May I ask if the control bar of the Able Player can be customized? As the size of the current player is too large for me that will affect the layout of the web page, so I want to hide some of the button, and make the player like YouTube or VideoJS that all control buttons are on the same row. Is there any way to customize it? Will it affect the accessibility?

Thank you.

**Comment by terrill** [comment]
@katlamen currently no buttons are optional.  Other than the standard controls that accompany most media players (play/pause, slider, and volume control), all other buttons are there because they play some role in accessibility.  Many of the buttons are added conditionally depending on which resources are available (e.g., captions, descriptions, chapters, transcript, sign language) so the player needs to be flexible enough to accommodate those buttons conditionally (unless you know for sure that you are always going to have/not have some of these resources).

I'm closing this particular issue for now, but there's an active conversation about this in issue #305 - feel free to weigh in over there.
