### ISSUE TITLE
Firefox has problems with certain files, and playlist clicks don't work after that

### ISSUE THREAD

**Issue by lardconcepts** [ableplayer/ableplayer#384]
Here's a player: https://kingston.talking-news.info/

Everything is shiny in Chrome, IE and Edge.

But Firefox doesn't seem to like the playlist, and particularly one particular file.

These audio links are likely to change this coming Friday, but for now... it stalls on track 17

https://audio.talking-newspapers.co.uk/users/kingston/online/KTN-Weekly/editions/20190907/00000017-K-T-N-1934.mp3

With the following error:

Media resource https://audio.talking-newspapers.co.uk/users/kingston/online/KTN-Weekly/editions/20190907/00000017-K-T-N-1934.mp3 could not be decoded, error: Error Code: NS_ERROR_DOM_MEDIA_DEMUXER_ERR (0x806e000c)

Strange thing is, the file plays perfectly when linked to directly, and mp3diags and mediainfo don't report anything unusual about the file.

Looks like this Firefox bug has been around for a while

https://stackoverflow.com/questions/44200990/html5-audio-player-in-firefox-is-not-working

I have also submitted this as a bug at https://bugzilla.mozilla.org/show_bug.cgi?id=1579837

A workaround is provided, but I do understand that it's not your issue to try and fix bad browsers! However, if you can, it would be lovely! 

Firefox 69.0 (64-bit)

**Comment by terrill** [comment]
@lardconcepts here's another (older) bug report related to the same issue: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1378687

Have you tried referencing the same URL in an HTML `<audio>` element, independent of Able Player? 
```
<audio controls preload="auto" src="https://audio.talking-newspapers.co.uk/users/kingston/online/KTN-Weekly/editions/20190907/00000017-K-T-N-1934.mp3">
```
If that results in the same error, you'll know for sure it's a browser issue, unrelated to Able Player. 

Also, it's not _solely_ a browser issue, since it only occurs with that one file. Compare to Track 04 from your playlist - they're approximate the same length and similar file sizes, but track 04 plays fine. To me, that suggests the Track 17 file is corrupt. Have you tried re-encoding it?

**Comment by terrill** [comment]
Closing this issue for now. Feel free to reopen it if you have additional questions or comments.
