### ISSUE TITLE
Ad Support for Installation with captions off by default

### ISSUE THREAD

**Issue by JoachimKunert** [ableplayer/ableplayer#394]
Your Player is excellent, but we decided not to use it because we want to have captions off by default. I believe you will lose a lot of possible distribution if you enforce that setting. Isn't it better to have a lot of users with the Ableplayer starting with captions off than no users at all?

**Comment by terrill** [comment]
@JoachimKunert we discussed this a lot when we first launched. It's equally simple to turn captions off as it is to turn them on. The question is: Which group of users should have to click that one time? We chose to put that minor inconvenience on people who are distracted by captions, rather than on people benefit from them or are dependent on them. Part of that decision is based on research, since there's a growing body of data that shows much higher engagement among users when captions are on. Here's some further reading:       

- [How close captioning Facebook videos can improve viewership ](https://instapage.com/blog/closed-captioning-mute-videos)
- [Research from 3PlayMedia and Discovery Digital Networks](https://www.3playmedia.com/customers/case-studies/discovery-digital-networks/)
- [More research from Facebook via 3PlayMedia](https://www.3playmedia.com/2016/02/12/captions-increase-viewership-for-facebook-video-ads-by-12/)
