### ISSUE TITLE
Playlist audio becoming muted on Android

### ISSUE THREAD

**Issue by givepraise** [ableplayer/ableplayer#395]
With latest ableplayer version, audio fails on Chrome 78 (Android) when switching tracks on playlist. When I open playlist the first track is able to play, once you switch to another track the audio no longer works. Recreated on https://ableplayer.github.io/ableplayer/demos/audio3.html

**Comment by terrill** [comment]
@givepraise this should be fixed in 1e9898be3c7b2751542eff2b3b6181a261ef3ebc
I confirmed the bug on various Android devices in Device Mode in Chrome DevTools; confirmed it's fixed using the same tool. I don't have easy access to an actual Android device though, so please reopen this issue if it continues to be a problem. Thanks!
