### ISSUE TITLE
Resume video after description is read doesn't work on IE11 and safari macos and ios

### ISSUE THREAD

**Issue by DavidGuijarro** [ableplayer/ableplayer#396]
After setup 'Automatically pause video when description starts', doesn't works well on IOS safari, macos safari and IE11. The video doesn't start again after pause

**Comment by DavidGuijarro** [comment]
An example of this issue https://ableplayer.github.io/ableplayer/demos/video5.html

**Comment by drbldgtl** [comment]
Has anyone managed to take a look at this issue?

**Comment by terrill** [comment]
@DavidGuijarro @drbldgtl the 'Automatically pause video when description starts' feature only works for text-based audio description, provided in a VTT file. The example you cited (Video Demo 5) uses a separate described video for its description. When description is mixed into the video, Able Player has no way of knowing when the description has started and stopped, so it can't automatically pause. 

Video demo #3 uses text-based description, so try that: 
https://ableplayer.github.io/ableplayer/demos/video3.html

I just tested it in Firefox, Chrome, and Safari on Mac OS (they all work), and on IE11 and Edge in Windows (Edge works, and IE11 works as expected). Internet Explorer does not support the Web Speech API (and never will), so in IE Able Player falls back to our old method of delivering text-based audio description. The description content is exposed at the designated start time in an ARIA live region, and it will be read aloud by a screen reader, not by the browser. The video will pause if the user has enabled that feature, but it won't start back up again because Able Player has no way of knowing when the screen reader is finished reading. So the user needs to manually resume playback. 

Hope that helps clarify.
