### ISSUE TITLE
Unable to change default seekInterval

### ISSUE THREAD

**Issue by hymen-da-man** [ableplayer/ableplayer#397]
I am trying to change the seekInterval from the default of 10 and set to fixed however whenever I make any changes to the default value, the rewind and fast forward stop working completely.
		
               `this.defaultSeekInterval = 2;
		this.useFixedSeekInterval = true;`

I've tried different combinations of values but can't seem to change it and have it work. In the readme it reference the data-seek-interval as an optional attribute but is there not a way to change the default?

**Comment by hymen-da-man** [comment]
My developer figured out how to work around this. Adding the extra seek-interval attribute to the audio tag on the page loading the controller worked;
`<audio id="audio1" width="500" data-able-player preload="auto" data-seek-interval="2">`
It's in the documentation as well.

**Comment by terrill** [comment]
@hymen-da-man you're correct that the `data-seek-interval` attribute is the expected way to override the default seek interval, which is calculated based on duration of media. Nevertheless, the variables you were trying to manipulate *should* work as you expected them too. That's been fixed in 52b90e9f5ce396c209af2804fe85d6f9c6ce1a1b
