### ISSUE TITLE
Player distortion with track-element included

### ISSUE THREAD

**Issue by lklende** [ableplayer/ableplayer#398]
I used the youtube2.html as sort of template for a script trying to get about the same soloution for one of my videos on YouTube, However it does not work. It seems like the 'track' element distort the videoplayer, which looses all the buttons. And the transcript which is loaded in youtube is not merged with the contnet of the local chapters file. The chapters file is a valid WEBVTT file. Can anybody tell me what is wrong? (By the way, the youtube2.html in the demos directory works perfect on my server). 
The video with its distortion can be seen here; https://www.metode.tips/ableplayer/TestVideo1.html

**Comment by terrill** [comment]
@lklende when I access your page in Firefox, I see an error in the developer console: "XML Parsing Error: syntax error", triggered by your VTT file in Line 1, Column 1. This probably means your server is delivering the wrong mime type for VTT files, which could be fixed by adding the following line to an .htaccess file on the server: 
`AddType text/plain vtt` 

Able Player should recover more gracefully from a VTT parse error, but that's another issue.

**Comment by terrill** [comment]
I'm closing this issue for now. Feel free to reopen though if you have additional questions or comments.
