### ISSUE TITLE
Base64 data as audio source

### ISSUE THREAD

**Issue by iceman2894** [ableplayer/ableplayer#399]
I can't get Base64 data to work as audio source .. any suggestions?

![image](https://user-images.githubusercontent.com/15612446/72753998-43346e00-3bcf-11ea-8f62-03a956c733fd.png)

**Comment by terrill** [comment]
@iceman2894 does your example play in the browser if you just use an HTML5 `<audio>` tag, independently of Able Player?  If not, then this isn't an Able Player problem. Able Player is just providing an alternative user interface to replace the browser's default HTML5 player. 

I haven't played at all with Base 64 media, but one thing that jumps out at me from your code example is the mime type. In your `src` attribute you have `data:audio/mp3` - should that be `data:audio/mpeg` ?  If it doesn't work in the browser's native browser, I suggest changing that to see if that helps.

**Comment by iceman2894** [comment]
I have solved this by adding the source programmatically for now
`AblePlayerInstances[0].media.src = <Base 64 String>;`

I will test using just HTML5 when i can and i will post back the results.

**Comment by terrill** [comment]
I tested this using PHP `base64_encode()` to encode the Able Player demo files, like so: 

```
<audio id="audio1" width="480" preload="auto" data-able-player data-skin="2020">
  <source type="audio/mpeg" src="<?php encodeMedia('audio/mpeg','smallf.mp3');?>"/>
  <source type="audio/ogg" src="<?php encodeMedia('audio/ogg','smallf.ogg');?>"/>
</audio>
```
```
<?php
function encodeMedia($mimeType,$fileName) {
  $filePath = '../media/'.$fileName;
  echo 'data:'. $mimeType.';base64,'.base64_encode(file_get_contents($filePath));
?>
```
I tested audio, video, and the poster image in Firefox, Chrome, and Safari, and it works fine in each. However, it also takes much longer to load the media files. I did some benchmarking using the *smallf* audio file and *wwa* video files that are included with Able Player. On average, if the file URLs are referenced directly (not Base 64 encoded), the audio file triggers the HTML media *canplay* event in 300ms, and *canplaythrough* just 1 or 2 ms after that. In contrast, if the same source files are Base 64 encoded, *canplay* is triggered in 2311 ms, and *canplaythrough* in 2336ms. For larger files the difference is even more pronounced. In my tests it took the video file about 10 times longer to load when encoded than when referenced directly. 

This might be misleading since I'm encoding on the fly using PHP, so maybe I'm just measuring the speed of the PHP `base64_encode()` function.  

This makes me curious though: Why are you wanting to use Base 64 encoding for your audio files @iceman2894? What's the benefit?

**Comment by iceman2894** [comment]
Sorry for the very late reply, and thanks for your interest in my issue,

I needed to use base64 because the files that i want to run are local files for the client side not on my server nor i want to upload them to my server so i just load the base64 in memory and push it to ablePlayer using jquery.
