### ISSUE TITLE
Should font-family names be translated in Caption Preferences dialog?

### ISSUE THREAD

**Issue by npostnik** [ableplayer/ableplayer#401]
In a translated version captions change to Times New Roman, if caption font is set (settings). The span wrapping the caption looks like this after changing the caption font:
`<div class="able-captions" style="font-family: Serifenschrift; font-size: 100%; color: white; background-color: black; opacity: 1; display: inline-block;">Ihre Webseiten-Besucher sind keine gesichtslose Masse<br>identischer Maus-Klicker</div>`
font-family: Serifenschrift is not a valid font name and therefore the browser drops back to using Times New Roman.

**Comment by terrill** [comment]
This raises an interesting question regarding localization. In the Captions Preferences dialog, users can choose font (sans-serif, serif, monospace, etc.) and foreground and background colors (yellow, black, white, etc.). Each of these options has been translated, but the bug here is that the translated text is mistakenly being used as the CSS value. Clearly the values must be in English, but what about the option text as it appears in the select fields within the Preferences dialog?  Do non-English readers in all languages understand English font family names? And what about colors? @rococode @Egyrs @ylahav @motchie @jannrobert @vierkantemeter @ShadowBB @mgmar22 @JediLin

**Comment by rococode** [comment]
I don't have any sources to back this up but I believe typically colors would be translated and font names would not (names in general are not translated). The thing with translating names is that a lot of English names may not have obvious (and thus, consistent) translations. Times New Roman, probably easy to translate. But things like Karla or Montserrat or Raleway or Calibri are much trickier names to translate so it's pretty typical to not bother.

It is more common to translate in languages without the Roman alphabet (e.g. Chinese) or with standard ways of phonetic translations (e.g. Japanese katakana). But I believe that's very much case by case.

**Comment by terrill** [comment]
Thanks @rococode. I looks like most of the people who translated Able Player chose not to translate font names. 
**Languages with font names not translated**
- ca
- es 
- he 
- it 
- ja 
- nl 

**Languages with font names translated**
- de 
- fr 
- nb 
- pt-br
- tr 
- zh-tw

A few of the non-translated languages did opt to translate "cursive". My inclination is to leave this up to the translators of the individual languages. If others feel strongly that font family should or should not be translated in a particular language, feel free to submit a pull request on the develop branch with the relevant translation file corrected (or just post your opinion here and I can make the change). 

Meanwhile, I'll fix the bug so the font-family CSS value is not translated.

**Comment by terrill** [comment]
Bug fixed in 669c172938ab47be32e86fc7c3c94f5ac9475d00
