### ISSUE TITLE
loading video and VTT files from local machine

### ISSUE THREAD

**Issue by devils13** [ableplayer/ableplayer#404]
Hi,

Just wondering if able player has built-in functionality to play a video file from the device as well as caption files.  I am running a language learning website. I thought it would be good to have the function due to copyright issues.  
This isn't an issue but, I didn't know where I could ask this question.  Sorry if this is not the right place for it.

many thanks,

**Comment by davidengebretson** [comment]
Is this a Vimeo file? Vimeo requires you host your VTT files locally.

Best,
David

**Comment by devils13** [comment]
Hi David,
I want to load a mp4 video and VTT files from machine. I sort of worked out loading a video file but have no idea how to do vtt files as I have very limited coding knowlede.
Cheers,

**Comment by terrill** [comment]
@devils13 If you have a local HTML page that includes a `<video>` element with one or more nested `<track>` elements, and you open that in your browser as a file (i.e.,  via File > "Open File" or using the file:/// protocol), most browsers will not load the VTT files due to security concerns. To get it to work locally, you would need to setup a web server on your local machine using something like [XAMPP](https://www.apachefriends.org/index.html).

**Comment by sprousecu** [comment]
I found that if you do not have a local server such as XAMPP, and just want to verify that AblePlayer is displaying correctly in your local browser, you can comment out the track elements in your local HTML page. Of course this also means you wont be able to view those commented elements like closed-captions until you launch your page from a website, or other server.
