### ISSUE TITLE
Can we force version to be 4.2.1?

### ISSUE THREAD

**Issue by perritoMedia** [ableplayer/ableplayer#417]
Is there a way to make sure the AblePlayer version on our site stays at version 4.2.1 to avoid overwriting customisations?

**Comment by terrill** [comment]
@perritoMedia sorry for the slow response. You can simply not upgrade in order to remain at 4.2.1.  However, by doing that you'll miss out on bug fixes, and maybe other cool features you might want. Would probably be best to fork this repo and take steps using git to keep your customized version in sync. Or, if your customizations might benefit others, consider filing a pull request.
