### ISSUE TITLE
WebVTT supported version

### ISSUE THREAD

**Issue by rgvcycling** [ableplayer/ableplayer#426]
My client is using a transcription service to create their webVTT files and they want to know what version of webVTT does AblePlayer support. The only thing that I could find was in the wiki pointing to Draft Community Group Report, 30 March 2018. Is that still the case?

Thanks,
Ray

**Comment by terrill** [comment]
Sorry for the slow response - I missed this earlier.  Yes, you're correct that we haven't done any further work to update the WebVTT parser. That's an open issue, #13 . 

Full support for WebVTT is a major undertaking, and we've been waiting for it to become a W3C Recommendation before doing any major work on it. It's a W3C Candidate Recommendation now, so getting closer, but it's stuck there since April 4 2019.

**Comment by rgvcycling** [comment]
Hey Terril, thanks for the update. This information is something that I can get back to the client with.
