### ISSUE TITLE
Select videos not loading in Able Player

### ISSUE THREAD

**Issue by youthelectronix** [ableplayer/ableplayer#446]
Having issues with select videos not playing in Able Player on our site. The downloadable versions will play in browser. Similar to issue #264 but have not identified any encoding issue. We have re-encoded with settings that appear to be fine to no avail. We are on the latest Player.

Example: Not playing
https://credo.library.umass.edu/view/full/murg25_m6_3-i001-001
https://credo.library.umass.edu/view/full/mufs001-th-film-i001

Example: Playing
https://credo.library.umass.edu/view/full/mums748-av-i002

Any thoughts?

**Comment by terrill** [comment]
@youthelectronix I'm not sure why one is playing and the others are not. You have two `<source>` elements, for WebM and MP4 versions respectively. The WebM version is triggering an error in the browser console. Since that's the first of your two sources, browsers should move on to the second source if they fail to load the first, but maybe that's not happening for some reason. Try removing the first `<source>` element, so you just have one source (the MP4 version). Browser support for MP4 is [almost universal](https://caniuse.com/mpeg4) now, so I think you're ok eliminating the WebM source, especially since you're including a download link. Let us know if that works.

**Comment by youthelectronix** [comment]
@terrill Thanks. We figured it out. Turns out it was a file naming issue. The player was looking to play a certain file and couldn't find it because the original file name did not match up.
