### ISSUE TITLE
Alble player for vimeo 

### ISSUE THREAD

**Issue by happysquiddesigns** [ableplayer/ableplayer#452]
HI,
I am a little technically challenged so hopefully, this question is not too stupid :)
My client uses this plugin for captioning for the university deaf community. He was hoping to have a search function for the trasncript. Students have asked about this option.

**Comment by terrill** [comment]
@happysquiddesigns since the transcript is added to the web page as HTML, it can be searched using the browser's built-in search functions. I personally don't think it's necessary to add functionality to Able Player that just replicates what's already available in browsers.

**Comment by terrill** [comment]
@happysquiddesigns just thought I'd elaborate on my earlier response to your question: Since the title of this issue is "Able Player for Vimeo", it's important to note that it's currently impossible for Able Player to generate an automatic transcript from captions if the video is hosted on Vimeo.  So, for Vimeo videos, there's no transcript at all for users to search.  For more information, see [Limitations of hosting captions and subtitles on YouTube or Vimeo](https://github.com/ableplayer/ableplayer#limitations-of-hosting-captions-and-subtitles-on-youtube-or-vimeo) in the README.
