### ISSUE TITLE
YouTube captions suddenly not appearing in AblePlayer

### ISSUE THREAD

**Issue by Hayhow** [ableplayer/ableplayer#478]
Hi,

Firstly, AblePlayer is a really great piece of work. Began work on our project this morning which uses AblePlayer and noticed that our YouTube videos are coming through without captions. They were working just fine yesterday. Issue can be seen on AblePlayer own YouTube example page.

https://ableplayer.github.io/ableplayer/demos/youtube.html

Can only assume YouTube have changed the way data is accessed.

**Comment by terrill** [comment]
Thanks for the heads up @Hayhow !  This indeed is due to major changes at Google/YouTube.  They seem to have pulled the plug on the *timedtext* API, which for years has been a dependable, albeit undocumented, means of getting access to YouTube caption files. I'm working on a solution. Stay tuned...

**Comment by terrill** [comment]
This is fixed in 2ab4fac434a3ff1c7b6b3ea1b7301e35bc305799  
This is currently only on the develop branch, but will be merged into the main branch as a new release (v4.4) very soon. 

Note that full Able Player functionality is no longer possible for YouTube videos unless captions and subtitles are hosted locally. There's a new section in the README with heading "Limitations of hosting captions and subtitles on YouTube or Vimeo" that explains this.
