### ISSUE TITLE
fallback 

### ISSUE THREAD

**Issue by mishav78** [ableplayer/ableplayer#484]
Can you provide the basic code if the browser doesn't work with able player to have it just use native controls like these
https://www.w3schools.com/html/html5_audio.asp

is that possible or browsers that don't support able player don't support native controls either? In that case what is the best option?

**Comment by terrill** [comment]
If the browser doesn't work with Able Player, it will display the HTML content that's nested inside the `<audio>` or `<video>` element. See the [Fallback Test page](../blob/main/demos/fallback.html) for examples (here's a [functioning example](https://ableplayer.github.io/ableplayer/demos/fallback.html) of the same page). 

Your question raises an interesting possibility: It might be possible to nest an `<audio>` or `<video>` element (without a **data-able-player** attribute inside the parent `<audio>` or `<video>` element (with a **data-able-player** attribute). So the outer media element is handled by Able Player, and if that fails, the browser can use the inner media element and provide the default HTML5 media player. If that fails, there would need to be a third level of fallback: HTML nested inside the inner `<audio>` or `<video>` element.  That's all hypothetical though, and doesn't currently work in Able Player (I just tried it to satisfy my curiosity). 

I can't justify spending more time on that because I think it's an extremely rare use case. What you said is probably true that if the browser can't handle Able Player, it doesn't support HTML5 media at all.
