### ISSUE TITLE
Missing controls for transcript and captions

### ISSUE THREAD

**Issue by cchavez-ga** [ableplayer/ableplayer#491]
The video controls for transcript and captions are no longer available anyone else have this issue and resolved it?

**Comment by terrill** [comment]
@cchavez-ga can you provide more detail? For example, are you using the latest version of Able Player? And are you hosting your videos and/or captions on YouTube or on your local web server?

**Comment by cchavez-ga** [comment]
Sure, we are using Version 1.0. The captions and videos are hosted on YouTube

**Comment by terrill** [comment]
Third-party access to captions on YouTube has changed. You'll need to upgrade to the latest version of Able Player (currently 4.4.1).  Even then, the only way to have full Able Player functionality with YouTube videos (e.g., an interactive transcript) is to host the caption files on your local web server. Otherwise Able Player has no access to the caption data.

**Comment by cchavez-ga** [comment]
Got it, thank you!
