### ISSUE TITLE
Accessibility: add legends to fieldsets, avoid empty big play button

### ISSUE THREAD

**Issue by bzgaLindner** [ableplayer/ableplayer#509]
Wave tool complains about the following issues with latest ableplayer (4.4.1):

1. `<button class="able-big-play-button icon-play" aria-hidden="true" tabindex="-1" style="width: 642px; height: 365.783px;"></button>`: button-tag should not be empty for screen readers --> insert `<span class="sr-only">Play</span>`
2. Fieldset "Captions" should contain legend-tag for screen readers --> add `<legend class="sr-only">Captions</legend>`
3. Fieldset "Descriptions" should contain legend-tag for screen readers --> add `<legend class="sr-only">Descriptions</legend>`
4. Fieldset "Transcript" should contain legend-tag for screen readers --> add `<legend class="sr-only">Transcript</legend>`

Thanks for this great project!

**Comment by terrill** [comment]
This is fixed in 4684b7b6d45c74bf6a1d67e3f7af30091c090674 albeit with a slightly different approach: 
- Change `<fieldset>` elements to `<div role="group">`
- Added `aria-labelledby` to each of these groups, referencing the id of the relevant label/heading. 

This has the same effect as fieldset/legend, and was tested with the latest versions of JAWS, NVDA, and VoiceOver (MacOS), all in Chrome, just to be sure.
